### ISSUE TITLE
lint

### ISSUE THREAD

**Issue by ventosus** [sjaehn/BSEQuencer#1]
Hi, whenever a new LV2 plugin pops up, I'm running it through my work-in-progress LV2-lint tool [1]. Here the output:

[lv2lint.log](https://github.com/sjaehn/BSEQuencer/files/2830994/lv2lint.log)

[1] https://git.open-music-kontrollers.ch/lv2/lv2lint/about/

**Comment by sjaehn** [comment]
Thank you for your important information. It's a lot.

I wanted to take my hands on, followed your link, installed lv2lint, and ...

... got a totally different output:

[BSEQuencer.log](https://github.com/sjaehn/BSEQuencer/files/2872867/BSEQuencer.log)

Lacking the symbols and linking issues. And exactly there I wanted to start with. What went wrong?

**Comment by sjaehn** [comment]
Hi ventosus,
my own question now solved.
[Fail] Symbols: solved,
[Fail] Version minor, [Fail] Version micro: Yes, will be added if status != experimental. Soon :-).

**Comment by ventosus** [comment]
> Lacking the symbols and linking issues. And exactly there I wanted to start with. What went wrong?

You have to enable the linker and symbol checks at compile time of lv2lint (and have libelf headers installed).

    meson -Delf-tests=true build

Sorry for the confusion
