### ISSUE TITLE
No type "uint"

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BSEQuencer#10]
https://github.com/sjaehn/BSEQuencer/blob/master/src/BSEQuencer.cpp#L629

C++ doesn't define the type ```uint```.

**Comment by sjaehn** [comment]
Thanks. Yes, you are right. Fixed in 250ec13c7ca8372a5be1bb34d9e2bd0da178d697.

Did this cause compiler errors with Clang/FreeBSD? I thought it should work fine due to the C includes (lv2, pugl, cairo, ...). At least it did on my systems (gcc/linux).

**Comment by yurivict** [comment]
FreeBSD.

**Comment by sjaehn** [comment]
Likely, `uint` is not defined in `sys/types.h` for all systems. Then, `uint` makes incompatibilty problems. I'll replace `uint` by` unsigned int` in all my repositories.
