### ISSUE TITLE
Host controlled mode not working in Carla

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#13]
When I set the mode menu to Host controlled, in Carla with JACK Transport enabled, and then I click play in Carla, I don't see anything happening in BSEQuencer nor is there MIDI output.

**Comment by sjaehn** [comment]
Did you connect it to a MIDI input (or did you use Carlas virtual keyboard)? And did you connect it to a MIDI output device (e.g., a synth or a sampler plugin)? The sequencer starts running if you press a key on a MIDI keyboard. And you should hear something if the pattern is not empty && the plugin is connected to a synth / sampler.
