### ISSUE TITLE
host controlled playback not working in Carla

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BSEQuencer#14]
host controlled playback not working in Carla, when transport in Carla is running nothing happens in bsequencer.

**Comment by sjaehn** [comment]
Duplicate of #13

The host controlled mode uses a MIDI input to trigger playback. Thus, it only works if:
1) Jack transport is on AND
2) B.SEQuenzr is connected to a MIDI input device (e.g., keyboard) AND
3) A MIDI key is pressed.

I hope this will help you. Otherwise please let me know.

**Comment by sjaehn** [comment]
Mode renamed to "Host & MIDI controlled" in 39dc558211b7a56ae484f72a7a9fc5bbf7e2345d

**Comment by mxmilkiib** [comment]
Might it be possible to have also a "Host controlled" mode where playback is always on if the transport is running?
