### ISSUE TITLE
add swing functionality

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BSEQuencer#15]
add swing functionality like you find in the step sequencer by robin gareus https://github.com/x42/stepseq.lv2

**Comment by sjaehn** [comment]
Thank you for your feedback. I know that this feature is lacking. 

TODO: There would be different ways to implement it:
(i) Allow pad duration > 1.00. This is a bit challenging for programming the sequencer play method I used.
(ii) As an own pad property. Problems see (i).
(iii) Allow to merge pads.

The tricky part will be keeping the controls functionality (like jumps and reverse playback).

**Comment by sjaehn** [comment]
I thought about it and I had three different ideas how to implement your suggested feature. All of them are complicated.

1. A swing slider as in x42 stepseq
This feature works brilliantly in Robins stepseq and I implemented it in one of the other B.Music plugins, in B.Choppr: https://github.com/sjaehn/BChoppr/commit/6a59e6be646a53572c6f585493cbee42969fb145. 
However, such a slider would really be complicated in B.SEQuencer. For the programmer and for the user. The key problem are the "control" features that allow to control the progression. X42 stepseq doesn't have this problem. If you have different step durations (swing != 1:1) and if you use row-specific controls, the progression of the sequencer will completely run out of sync. This would be really hard to understand for the user. And a lot of programming work as the sequencer core (that uses a fixed time interval for progression) needs to be rewritten to implement this feature.

2. Define the step duration for each step
I liked the idea but there are the same problems as in 1.

3. Merge pads
Merging pads would allow to play notes of different durations without pausing. This would be an indirect way to implement something like a swing function. The tricky part are the controls as I mentioned before.

I decided to take version 3, implemented in d87bb4a13efd31cfca89825670dbcbc4e45d3a3c.

**Comment by grammoboy2** [comment]
On 4/29/20 10:11 PM, sjaehn wrote:
>
> I thought about it and I had three different ideas how to implement 
> your suggested feature. All of them are complicated.
>
> 1.
>
>     A swing slider as in x42 stepseq
>     This feature works brilliantly in Robins stepseq and I implemented
>     it in one of the other B.Music plugins, in B.Choppr:
>     sjaehn/BChoppr@6a59e6b
>     <https://github.com/sjaehn/BChoppr/commit/6a59e6be646a53572c6f585493cbee42969fb145>.
>     However, such a slider would really be complicated in B.SEQuencer.
>     For the programmer and for the user. The key problem are the
>     "control" features that allow to control the progression. X42
>     stepseq doesn't have this problem. If you have different step
>     durations (swing != 1:1) and if you use row-specific controls, the
>     progression of the sequencer will completely run out of sync. This
>     would be really hard to understand for the user. And a lot of
>     programming work as the sequencer core (that uses a fixed time
>     interval for progression) needs to be rewritten to implement this
>     feature.
>
> 2.
>
>     Define the step duration for each step
>     I liked the idea but there are the same problems as in 1.
>
> 3.
>
>     Merge pads
>     Merging pads would allow to play notes of different durations
>     without pausing. This would be an indirect way to implement
>     something like a swing function. The tricky part are the controls
>     as I mentioned before.
>
> I decided to take version 3, implemented in d87bb4a 
> <https://github.com/sjaehn/BSEQuencer/commit/d87bb4a13efd31cfca89825670dbcbc4e45d3a3c>.
>
Thanks!
>

**Comment by sjaehn** [comment]
Back to the the roots. I haven't thought about it before, but it was possible to create swing patterns with trioles even in the old version (before 1.3.0). Without swing functionality and without merging pads. How it works? Take a look to the Jazz Swing Cymbal Beat preset added in c58887b90adca7a52f8462852d4eaf793fc89d45 .
