### ISSUE TITLE
display velocity number

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BSEQuencer#16]
display velocity number, now you've no idea what values you're working with. The color is not very clear either. Again, see the step sequencer by Robin Gareus.

**Comment by sjaehn** [comment]
There are three options to see the velocity:
1) The color (not the best, I agree)
2) Displayed (together with pitch and duration) on hover over the respective pad.
3) Pick the pad (right click or use the pick tool) and you will see the velocity value on the dial in the toolbox right to the pattern.

As each pad has more than one propery AND there are also the playback symbols there is no space on the pad to display the velocity value.
