### ISSUE TITLE
Change GUI looks

### ISSUE THREAD

**Issue by grammoboy2** [sjaehn/BSEQuencer#18]
Without taking pills or other drugs, this GUI is hurting your eyes after exactly 1 minute and 23 seconds after working with it and it's hard to read as well. 

If I want this sensation, I'll stare into some car lights for a few minutes. I don't need a stepsequencer for this. 

Take a look at the step sequencer of robin gareus again. Man, just plain simple. I like.

**Comment by sjaehn** [comment]
Feel free to use Robins sequencer.
