### ISSUE TITLE
Tooltips time?

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#19]
Would it be possible if the tooltips could come up slightly quicker after hovering the mouse pointer over a button, etc? See the time it takes for tooltips for titles of tabs in a browser.

**Comment by sjaehn** [comment]
https://github.com/sjaehn/BSEQuencer/blob/master/src/BWidgets/Focusable.hpp#L21 BWIDGETS_DEFAULT_FOCUS_IN_MS can be set to a value lower than default 1000. I can reduce the value to some 200 in B.Widgets for all B.Music plugins.

**Comment by sjaehn** [comment]
Changed in cabfd0ae74be10ced696d81a9660a75fd47f9664 .
