### ISSUE TITLE
Make UI resizable

### ISSUE THREAD

**Issue by ventosus** [sjaehn/BSEQuencer#2]
Hi, thanks for the plugin.

The plugin UI seems to be fixed-size (which can be okay). But for my display (1366x768) its minimal size is just too big, e.g. it does not fit.

What about making it just fixed-aspect + resizable ?
Or even better: Make it fully resizable for all the tiling-window-manager-lovers :)

**Comment by sjaehn** [comment]
Thank you for your feedback. Indeed, I didn't taken in account the lower resolution displays. I also worry about other plugins that simply do fit onto my screen (which is even bigger).

I thought about it. I see three possible options:
(i) I can squeeze it to fit in 768 lines. This could be a quick fix, but it isn't the nicest for big screen.
(ii) I can add scrollbars. I don't like them and they are not in the BWidgets toolkit yet. But it could also be a quick fix.
(iii) I can make the UI fully scaleable. To date, the plugin UI is fixed size as the underlying BWidgets toolkit uses fixed positions. The toolkit itself uses Cairo vector drawing. But the toolkit is based on lots of non scaling-friendly image surfaces.

Somehow, I prefer option (iii). But it will be some work. Thus it will take a while. I add it to TODO.

**Comment by ventosus** [comment]
Hey, thanks

(i) I also have a 800x640 display laying around :)
(iii) A (terrible) bloody fix would be to not directly draw to pugl's cairo surface, but instead to an intermediary cairo memory surface and then scale-plot the latter to pugl's cairo surface. Could be reasonable for minimizing, at least.

p.s. you'll probably need some kind of scaling no matter what, because there are people with HiDPI displays that will come along complaining ...

**Comment by sjaehn** [comment]
Thought a while about it. I discarded my initial intention to add a zoom to the toolkit as this would either result in zooming the underlying bitmap surfaces (the "(terrible) bloody fix" that would only delight minecraft fans) or performance killing redraw of all widgets above the zooming widget on each change.

So, I directly added a scaling factor (sz) to the GUI in commit c147a9d. It now works on small display, where its minimal size is set to down to 600 x 410 (I've doubts if it makes sense, but it works) or some 800 x 540. Upscaling works too. You can also use it in the full screen mode.

There are two expected "abnormalities", I won't fix at this moment:
1) As the background image is a bitmap, upscaling on big high resolution displays will result in the mentioned minecraft effect.
2) As some widgets contain elements with a static size (:-(), these widgets (e.g., PopupListBox) will not be scaled 1:1 and thus may look abnormally after scaling.

Everything else is a bug.
