### ISSUE TITLE
'Host controlled' mode?

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#23]
Might it be possible to also have a "Host controlled" mode where playback is always on if the transport is running?

**Comment by sjaehn** [comment]
A host controlled autoplay - why not? I'll keep it in mind for version 1.8.

**Comment by sjaehn** [comment]
Did you mean this 5f6b64dc461792a8d45ab28e738ee8de06ec5e4d and this 79bd0e731f9faa21ca596dcec02e179342680de4 ?

**Comment by mxmilkiib** [comment]
Yes, thank you :)
