### ISSUE TITLE
Custom scale dialog can become unavailable via dragging

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#25]
I dragged it off the 'bottom' of the plugin UI and let go, now I can't retrieve it.

Edit: I can get it back by closing and reopening the window.

**Comment by sjaehn** [comment]
I know, you can drag dialogs, message boxes, ... out of the window. The only way to get them back is closing and re-opening the GUI.

**Comment by mxmilkiib** [comment]
How about having a 16px edge around the dialog that can't be hidden so the dialog can be moved out the way temporarily but not lost without reopen?

**Comment by sjaehn** [comment]
I'm thinking about to implement such a property in the B.Widgets TK. So it will be available for all B.Music plugins.

**Comment by sjaehn** [comment]
Fixed in a4e035e9caad734e3fa363afca7dd9851dcd6943. It's only a 4 px border. But this was done without any additional member variable.
