### ISSUE TITLE
Local install

### ISSUE THREAD

**Issue by tank-trax** [sjaehn/BSEQuencer#29]
this could be helpful to mention for your plugins for people wishing to install locally rather than system wide

`make install LV2DIR=~/.lv2`

also thanks for having that built into the script :-)

**Comment by sjaehn** [comment]
Thanks for info. The README.md is on an old version, indeed. Will be updated next time.

**Comment by sjaehn** [comment]
Added in 9da5b6a90afdbbcd18709f5a09a059daa6c6f750 .
