### ISSUE TITLE
Add openSUSE packages in README

### ISSUE THREAD

**Issue by KottV** [sjaehn/BSEQuencer#30]
Hi

Packages for openSUSE are available for a long time https://software.opensuse.org/package/BSEQuencer and for other your plugins of-course.
I believe it deserve to be mentioned in README alongside other distros.

I can make PR if it's a preferable way.

**Comment by sjaehn** [comment]
Thanks to mention. I've to admit that I only frequently check for new releases. I'll link this package and I'll check the other plugins for openSUSE releases.

**Comment by sjaehn** [comment]
Added in 1b4f94552678ab82de0f2af266e1b717fd21e0ca
