### ISSUE TITLE
Packaged in the AUR

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#4]
An FYI that I've added this to the AUR - https://aur.archlinux.org/packages/bsequencer-git

**Comment by mxmilkiib** [comment]
Also, to save on issues, I've also created https://aur.archlinux.org/packages/bslizr-git/ and https://aur.archlinux.org/packages/bshapr-git/

**Comment by sjaehn** [comment]
Thanks :-)
