### ISSUE TITLE
Character for # notes appears as a box

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#5]
![rose_2019-04-17-22:03:24](https://user-images.githubusercontent.com/108225/56320939-388b0b00-615d-11e9-8204-c8a38e5ebe70.png)

**Comment by sjaehn** [comment]
Thank you for reporting. I was afraid that this will happen to some users, as the widget extensively uses Unicode symbols for sharp and flat signatures. And also uses Unicode symbols for the controls and for the play / stop button.

**Comment by sjaehn** [comment]
Bugfix (hopefully) completed:

- Sharp/flat symbols: Replace Unicode by ASCII127 in d318bebb46d92958cf292c289ffe0937bfaa5546
- Substitute button unicode symbols by hardcoded symbols (bugfix) in cf35c227f1db6746e04e485e5c27c7a7594c0daf
- Substitute remaining Unicode symbols (edit tool that is shown following selection of a user scale, close symbol in scale editor) in 5f91b04232981599e1e5d68d5cda9a449690c1d8

**Comment by mxmilkiib** [comment]
Sorted, thanks :)
