### ISSUE TITLE
Cannot set play mode back to Host controlled

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BSEQuencer#6]
After I change it, it's stuck on Autoplay.

**Comment by sjaehn** [comment]
It sticks on "autoplay" or is there no transport of the cursor line after change to "host controlled" ?

The first would really be a bug, the second is a "feature". 

Also this plugin needs Jack transport to get speed and position data (beat, bar, ...) from the host in the "host controlled" mode. "Autoplay" works independently.

**Comment by mxmilkiib** [comment]
Aaah, the menu is not displaying properly.

When I click on it, it looks like;
![rose_2019-04-20-06:38:21](https://user-images.githubusercontent.com/108225/56453220-151bb800-6337-11e9-929f-b8aaa98793e8.png)

then after clicking and it's on Autoplay mode, the open menu looks like this;
![rose_2019-04-20-06:38:28](https://user-images.githubusercontent.com/108225/56453223-1f3db680-6337-11e9-9cc3-3eb81ce53bb8.png)

but if I click the arrow at the bottom, I see the Host Controlled option;
![rose_2019-04-20-06:38:33](https://user-images.githubusercontent.com/108225/56453227-2369d400-6337-11e9-91d5-77468c1345d2.png)

**Comment by sjaehn** [comment]
I guess your screen resolution is < 1200 x 820 (which cause GUI resize) or you manually resized the GUI. The popup widgets I used do not resize in a fully symetric way, unfortunately. But what you describe was not expected (but also not fully unexpected). I think it is a rounding-related bug. I will take a closer look in this next week.

**Comment by mxmilkiib** [comment]
You are right. I manually resized. This is what the plugin looks like before resizing on my laptop main screen;

![rose_2019-04-20-22:24:21](https://user-images.githubusercontent.com/108225/56462447-17bff100-63bb-11e9-8ace-f23249f65efc.png)

**Comment by sjaehn** [comment]
Fixed in de62fd78ec3f5beb4836f1a4f8c9c236fc2bf4c6

**Comment by mxmilkiib** [comment]
Also sorted, thanks!
