### ISSUE TITLE
Build fails with clang-8: implicit instantiation of undefined template 'std::__1::array<bool, 14>', etc

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BSEQuencer#7]
Build fails on FreeBSD with clang8, see the full log: https://people.freebsd.org/~yuri/bsequencer-lv2-failure.txt

src/BWidgets/Widget.hpp seems to be missing ```#include <array>```, etc, etc.

**Comment by sjaehn** [comment]
Thanks for information. Indeed, `#include <array>` is missing. First look, this seems to be the cause for most / all (?) errors (tl;dr). I'm currently rewriting large parts of BWidgets. So, I will take this along. But this still takes a few days. If you can't wait, try to include it into src/BWidgets/Widget.hpp and please inform me about the compiler output.

**Comment by sjaehn** [comment]
Bug `#include <array>` fixed in 265b06cde916b4f4361c21e2420e19dd59857e68

**Comment by yurivict** [comment]
Thanks for fixing this.
